import { findProject } from "./portfolio";
import type { AnalysisCost, Brief } from "./schema";

export type Verdict = "worth_it" | "inspiration" | "discard";

export interface Review {
  verdict: Verdict | null;
  notes: string;
}

/**
 * One map for the screen and the export, so the word a reviewer clicks is the word that
 * reaches the proposal document.
 *
 * "Not now" rather than "Discard": a rejected proposal stays in the exported brief, with the
 * reviewer's reason attached, so nobody proposes the same thing again in three months.
 * "Discard" promised a deletion that does not happen.
 */
export const VERDICT_LABEL: Record<Verdict, string> = {
  worth_it: "Worth it",
  inspiration: "Inspiration",
  discard: "Not now",
};

const EFFORT_LABEL = { S: "S (< 2 weeks)", M: "M (2-6 weeks)", L: "L (> 6 weeks)" };

/**
 * The reviewed brief as markdown, ready to paste into the CRM or a proposal document.
 * This is the actual output of the tool: the screen is where you decide, this is what you keep.
 */
export function buildMarkdown(
  brief: Brief,
  reviews: Review[],
  cost: AnalysisCost,
  warnings: string[] = [],
): string {
  const lines: string[] = [];

  lines.push("# Discovery brief", "");
  lines.push(brief.clientSummary, "");

  lines.push("## Detected pains", "");
  for (const pain of brief.pains) {
    lines.push(`- **${pain.title}** — ${pain.detail}`);
  }
  lines.push("");

  lines.push("## Proposals", "");
  brief.proposals.forEach((proposal, index) => {
    const review = reviews[index] ?? { verdict: null, notes: "" };
    const matched = proposal.reuse.projectId
      ? findProject(proposal.reuse.projectId)
      : undefined;

    lines.push(`### ${index + 1}. ${proposal.title}`, "");
    lines.push(`- **Verdict:** ${review.verdict ? VERDICT_LABEL[review.verdict] : "not reviewed"}`);
    lines.push(`- **Effort:** ${EFFORT_LABEL[proposal.effort]}`);
    lines.push(
      `- **Reuse:** ${proposal.reuse.level}${matched ? ` — ${matched.name} (\`${matched.id}\`)` : ""}`,
    );
    lines.push(`- **Why:** ${proposal.reuse.why}`);
    lines.push("", proposal.whatItDoes, "");
    if (review.notes.trim()) {
      lines.push(`> **Reviewer notes:** ${review.notes.trim()}`, "");
    }
  });

  if (brief.openQuestions.length > 0) {
    lines.push("## Open questions for the next call", "");
    for (const question of brief.openQuestions) lines.push(`- ${question}`);
    lines.push("");
  }

  if (brief.riskFlags.length > 0) {
    lines.push("## Risk flags", "");
    for (const risk of brief.riskFlags) lines.push(`- ${risk}`);
    lines.push("");
  }

  if (warnings.length > 0) {
    lines.push("## Warnings from the analysis", "");
    for (const warning of warnings) lines.push(`- ${warning}`);
    lines.push("");
  }

  lines.push("---", "");
  lines.push(
    `_Generated by Discovery Assistant with ${cost.model}. ${cost.inputTokens.toLocaleString("en-US")} in / ${cost.outputTokens.toLocaleString("en-US")} out tokens, about $${cost.estimatedUsd.toFixed(4)}. Reviewed by a human before use._`,
  );

  return lines.join("\n");
}
